#!/bin/sh

# notify if vim is not installed
test -z "$(which vim)" && echo "vim not installed on system"

# download vim-plug
if [ ! -f ~/.vim/autoload/plug.vim ]; then
    echo "plug.vim not installed"
    # curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# link vimrc
ln -sf "$PWD/vimrc" "$HOME/.vimrc"
