filetype on
filetype plugin indent on

set number
set splitright
set splitbelow
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent
set fileformat=unix
set bg=dark

call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'tomasiser/vim-code-dark'
Plug 'sheerun/vim-polyglot'
call plug#end()

" golang syntax
" let g:go_highlight_types = 1
" let g:go_highlight_fields = 1
" let g:go_highlight_functions = 1
" let g:go_highlight_function_calls = 1
" let g:go_highlight_operators = 1
" let g:go_highlight_extra_types = 1
" let g:go_highlight_variable_declarations = 1
" let g:go_highlight_variable_assignments = 1

syntax enable
autocmd BufNewFile,BufReadPost *.go set filetype=go
