#!/bin/bash
test -z "$1" && echo "pdbget: no pdb code given" && exit 1
code=${1,,} # use either caps or lowercase when calling script
wget -nc -O "$code.pdb" "https://files.rcsb.org/download/$code.pdb"
