#!/bin/bash
x='\e[0m'     # reset
k='\e[90m'    # blacK
r='\e[91m'    # Red
g='\e[92m'    # Green
y='\e[93m'    # Yellow
b='\e[94m'    # Blue
m='\e[95m'    # Magenta
c='\e[96m'    # Cyan
w='\e[97m'    # White
bk='\e[1;90m' # Bold blacK
br='\e[1;91m' # Bold Red
bg='\e[1;92m' # Bold Green
by='\e[1;93m' # Bold Yellow
bb='\e[1;94m' # Bold Blue
bm='\e[1;95m' # Bold Magenta
bc='\e[1;96m' # Bold Cyan
bw='\e[1;97m' # Bold White

echo -e "${c}dap${x} - ${g}delete axound current paragraph${x}"
echo -e "${c}dip${x} - ${g}delete current paragraph${x}"
echo -e "${c}yap${x} - ${g}yank around current paragraph${x}"
echo -e "${c}yip${x} - ${g}yank current paragraph${x}"
echo -e "${c}ea ${x} - ${g}append to current word${x}"
echo -e "${c}cw ${x} - ${g}change to end of current word${x}"
echo -e "${c}ciw${x} - ${g}change current word${x}"
echo -e "${c}caw${x} - ${g}change around current word${x}"
echo -e "${c}dw ${x} - ${g}delete to beginning of next word${x}"
echo -e "${c}daf${x} - ${g}delete current function${x}"
echo -e "${c}yaf${x} - ${g}yank current function${x}"
echo -e "${c}dif${x} - ${g}delete current inner function${x}"
echo -e "${c}yif${x} - ${g}yank current inner function${x}"
echo -e "${c}dd${x}  - ${g}delete the current line${x}"
echo -e "${c}D${x}   - ${g}delete the end of a line${x}"
echo -e "${c}x${x}   - ${g}delete a single character${x}"
echo -e "${c}gu${x}  - ${g}change to lowercase up to motion${x}"
echo -e "${c}gU${x}  - ${g}change to uppercase up to motion${x}"
echo -e "${c}f${x}   - ${g}find to specific character inline, useful for yank / delete${x}"
echo -e "${c}yf\"${x} - ${g}yank a string incluing the quotes when cursor is on starting \"${x}"
