#!/bin/bash
if [[ -t 1 ]]; then
    x='\e[0m'  # reset
    k='\e[90m' # blacK
    r='\e[91m' # Red
    g='\e[92m' # Green
    y='\e[93m' # Yellow
    b='\e[94m' # Blue
    m='\e[95m' # Magenta
    c='\e[96m' # Cyan
    w='\e[97m' # White
fi

colorize() {
    printf "$c%-5s$x - $g%s$x\n" "$1" "$2"
}

colorize "dap" "delete around current paragraph"
colorize "dip" "delete current paragraph"
colorize "yap" "yank around current paragraph"
colorize "ip" "yank current paragraph"
colorize "ea" "append to current word"
colorize "cw" "change to end of current word"
colorize "ciw" "change current word"
colorize "caw" "change around current word"
colorize "dw " "delete to beginning of next word"
colorize "daf" "delete current function"
colorize "yaf" "yank current function"
colorize "dif" "delete current inner function"
colorize "yif" "yank current inner function"
colorize "dd" "delete the current line"
colorize "D" "delete the end of a line"
colorize "x" "delete a single character"
colorize "gu" "change to lowercase up to motion"
colorize "gU" "change to uppercase up to motion"
colorize "f" "find to specific character inline, useful for yank / delete"
colorize "yf\"" "yank a string incluing the quotes when cursor is on starting \""
