#!/bin/bash
if [[ -t 1 ]]; then
    x='\e[0m'  # reset
    k='\e[90m' # blacK
    r='\e[91m' # Red
    g='\e[92m' # Green
    y='\e[93m' # Yellow
    b='\e[94m' # Blue
    m='\e[95m' # Magenta
    c='\e[96m' # Cyan
    w='\e[97m' # White
fi

high_light() {
    printf "$c%-5s$x - $g%s$x\n" "$1" "$2"
}

high_light "dap" "delete around current paragraph"
high_light "dip" "delete current paragraph"
high_light "yap" "yank around current paragraph"
high_light "ip" "yank current paragraph"
high_light "ea" "append to current word"
high_light "cw" "change to end of current word"
high_light "ciw" "change current word"
high_light "caw" "change around current word"
high_light "dw " "delete to beginning of next word"
high_light "daf" "delete current function"
high_light "yaf" "yank current function"
high_light "dif" "delete current inner function"
high_light "yif" "yank current inner function"
high_light "dd" "delete the current line"
high_light "D" "delete the end of a line"
high_light "x" "delete a single character"
high_light "gu" "change to lowercase up to motion"
high_light "gU" "change to uppercase up to motion"
high_light "f" "find to specific character inline, useful for yank / delete"
high_light "yf\"" "yank a string incluing the quotes when cursor is on starting \""
